create type public.site_element_type as enum ('header', 'footer');

create table public.site_elements (
    id bigint generated by default as identity primary key,
    organization_id uuid references public.organizations not null,
    type public.site_element_type not null,
    content jsonb,
    published boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint unique_organization_element_type unique (organization_id, type)
);

alter table public.site_elements enable row level security;

create policy "Allow public read access to published site elements"
on public.site_elements
for select
to anon
using (published = true);

create policy "Allow org members full access to their own site elements"
on public.site_elements
for all
to authenticated
using (
    (
        select auth.uid()
    ) in (
        select om.user_id
        from organization_members om
        where om.organization_id = site_elements.organization_id
    )
);
